-- =============================================================================================
-- 🚀 MASTER SETUP SCRIPT: Snowflake Ops & Intelligence Platform
-- =============================================================================================
-- USE THIS SCRIPT for Internal Hosting (Native App Mode).
-- It sets up the Database, Warehouse, Application, and ALL required Security/AI permissions.
--
-- DO NOT RUN 'setup.sql' or 'setup_dummy.sql' if you are using this one.
--
-- RUN AS: ACCOUNTADMIN
-- =============================================================================================

USE ROLE ACCOUNTADMIN;

-- 0. Set up Warehouse
CREATE WAREHOUSE IF NOT EXISTS SNOWFLAKE_OPS_APP_WH 
  WAREHOUSE_SIZE = XSMALL 
  AUTO_SUSPEND = 60 
  AUTO_RESUME = TRUE;
USE WAREHOUSE SNOWFLAKE_OPS_APP_WH;

-- 1. Create Application Package
CREATE APPLICATION PACKAGE IF NOT EXISTS SNOWFLAKE_OPS_PACKAGE;

-- 2. Create Schema for Stage (CRITICAL: Stage needs a schema inside the package)
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_OPS_PACKAGE.STAGE_CONTENT;

-- 3. Create Data Structure for persistence
-- This database will store your app settings, budgets, and cached metrics
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_OPS_APP_DATA;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_OPS_APP_DATA.APP_CONTEXT;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_OPS_APP_DATA.APP_ANALYTICS;

-- Table DDL for persistence
CREATE TABLE IF NOT EXISTS SNOWFLAKE_OPS_APP_DATA.APP_CONTEXT.PLATFORM_SETTINGS (
    SETTING_KEY VARCHAR PRIMARY KEY,
    SETTING_VALUE VARCHAR,
    DESCRIPTION VARCHAR,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SNOWFLAKE_OPS_APP_DATA.APP_CONTEXT.BUDGET_ALERTS (
    ALERT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    ALERT_NAME VARCHAR,
    ALERT_TYPE VARCHAR,
    TARGET_NAME VARCHAR,
    THRESHOLD_CREDITS FLOAT,
    THRESHOLD_PERCENTAGE FLOAT,
    NOTIFICATION_CHANNEL VARCHAR DEFAULT 'DASHBOARD',
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS SNOWFLAKE_OPS_APP_DATA.APP_ANALYTICS.METADATA_CACHE (
    CACHE_KEY VARCHAR PRIMARY KEY,
    CACHE_VALUE VARIANT,
    EXPIRY_TIME TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS SNOWFLAKE_OPS_APP_DATA.APP_CONTEXT.WAREHOUSE_CONTEXT (
    WAREHOUSE_NAME VARCHAR PRIMARY KEY,
    PURPOSE VARCHAR DEFAULT 'GENERAL',
    SIZE VARCHAR,
    COST_PROFILE VARCHAR DEFAULT 'BALANCED',
    CONCURRENCY_TOLERANCE VARCHAR DEFAULT 'MEDIUM',
    OWNER_TEAM VARCHAR,
    NOTES VARCHAR,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SNOWFLAKE_OPS_APP_DATA.APP_CONTEXT.TABLE_CONTEXT (
    DATABASE_NAME VARCHAR,
    SCHEMA_NAME VARCHAR,
    TABLE_NAME VARCHAR,
    FRESHNESS_REQUIREMENT VARCHAR DEFAULT 'DAILY',
    ACCESS_FREQUENCY VARCHAR DEFAULT 'UNKNOWN',
    IS_CRITICAL BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (DATABASE_NAME, SCHEMA_NAME, TABLE_NAME)
);

CREATE TABLE IF NOT EXISTS SNOWFLAKE_OPS_APP_DATA.APP_CONTEXT.TEAM_ATTRIBUTION (
    USER_NAME VARCHAR PRIMARY KEY,
    TEAM_NAME VARCHAR,
    DEPARTMENT VARCHAR,
    COST_CENTER VARCHAR,
    BUDGET_LIMIT_CREDITS FLOAT,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SNOWFLAKE_OPS_APP_DATA.APP_ANALYTICS.QUERY_BENCHMARK (
    BENCHMARK_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_TEXT VARCHAR,
    QUERY_HASH VARCHAR,
    RUN_TYPE VARCHAR, -- 'BASELINE' or 'OPTIMIZED'
    PREDICTED_COST_CREDITS FLOAT,
    ACTUAL_COST_CREDITS FLOAT,
    PREDICTED_TIME_MS NUMBER,
    ACTUAL_TIME_MS NUMBER,
    BYTES_SCANNED NUMBER,
    WAREHOUSE_USED VARCHAR,
    WAREHOUSE_SIZE VARCHAR,
    OPTIMIZATION_APPLIED VARCHAR,
    COST_SAVINGS_CREDITS FLOAT,
    TIME_SAVINGS_MS NUMBER,
    RUN_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. Create Stage for App Files
CREATE OR REPLACE STAGE SNOWFLAKE_OPS_PACKAGE.STAGE_CONTENT.APP_STAGE 
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = '|' SKIP_HEADER = 1);

-- INSTRUCTION: Upload ALL app files to the root of this stage.
-- CRITICAL: 'manifest.yml' MUST be in the root of the stage.
--
-- From your project root, run:
-- snowsql -q "put file://./manifest.yml @SNOWFLAKE_OPS_PACKAGE.STAGE_CONTENT.APP_STAGE auto_compress=false overwrite=true;"
-- snowsql -q "put file://./streamlit_app.py @SNOWFLAKE_OPS_PACKAGE.STAGE_CONTENT.APP_STAGE auto_compress=false overwrite=true;"
-- snowsql -q "put file://./environment.yml @SNOWFLAKE_OPS_PACKAGE.STAGE_CONTENT.APP_STAGE auto_compress=false overwrite=true;"
-- snowsql -q "put file://./app/* @SNOWFLAKE_OPS_PACKAGE.STAGE_CONTENT.APP_STAGE auto_compress=false overwrite=true;"
-- snowsql -q "put file://./pages/* @SNOWFLAKE_OPS_PACKAGE.STAGE_CONTENT.APP_STAGE/pages auto_compress=false overwrite=true;"

-- 5. Create Application Object
CREATE APPLICATION IF NOT EXISTS SNOWFLAKE_OPS_APP
  FROM APPLICATION PACKAGE SNOWFLAKE_OPS_PACKAGE
  USING '@SNOWFLAKE_OPS_PACKAGE.STAGE_CONTENT.APP_STAGE';

-- 6. Grant Required Privileges (CRITICAL for Advanced Features)
-- 
-- "IMPORTED PRIVILEGES" on the SNOWFLAKE database is the KEY permission.
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO APPLICATION SNOWFLAKE_OPS_APP;

-- Allow app to access its own storage database
GRANT USAGE ON DATABASE SNOWFLAKE_OPS_APP_DATA TO APPLICATION SNOWFLAKE_OPS_APP;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SNOWFLAKE_OPS_APP_DATA TO APPLICATION SNOWFLAKE_OPS_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE SNOWFLAKE_OPS_APP_DATA TO APPLICATION SNOWFLAKE_OPS_APP;

-- Allow app to use Cortex (for AI Analyst & AI Optimizer)
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO APPLICATION SNOWFLAKE_OPS_APP;

-- Allow app to use Warehouse
GRANT USAGE ON WAREHOUSE SNOWFLAKE_OPS_APP_WH TO APPLICATION SNOWFLAKE_OPS_APP;

-- 7. Create Roles for Users (RBAC)
-- Create a Power User role that has access to Cost/Usage data WITHOUT being AccountAdmin
CREATE ROLE IF NOT EXISTS SNOWFLAKE_OPS_ADMIN;
CREATE ROLE IF NOT EXISTS SNOWFLAKE_OPS_USER;

-- Grant permissions to the Admin Role
GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE SNOWFLAKE_OPS_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE SNOWFLAKE_OPS_ADMIN;

-- Grant App Access to the Roles
GRANT USAGE ON APPLICATION SNOWFLAKE_OPS_APP TO ROLE SNOWFLAKE_OPS_ADMIN;
GRANT USAGE ON APPLICATION SNOWFLAKE_OPS_APP TO ROLE SNOWFLAKE_OPS_USER;
GRANT USAGE ON WAREHOUSE SNOWFLAKE_OPS_APP_WH TO ROLE SNOWFLAKE_OPS_ADMIN;
GRANT USAGE ON WAREHOUSE SNOWFLAKE_OPS_APP_WH TO ROLE SNOWFLAKE_OPS_USER;

-- 8. Launch Instructions
-- Grant these roles to your users:
-- GRANT ROLE SNOWFLAKE_OPS_ADMIN TO USER <user_name>;
-- GRANT ROLE SNOWFLAKE_OPS_USER TO USER <user_name>;

-- ============================================================================
-- CORTEX AI SETUP (Optional - Requires Premier Edition or Higher)
-- ============================================================================
-- If you are in a restricted region for AI features, run this as ACCOUNTADMIN:
-- ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

