-- ==============================================================================
-- SNOWFLAKE OPS INTELLIGENCE — GIT-BASED SQL-ONLY DEPLOYMENT
-- ==============================================================================
-- ZERO-CLONE INSTALL: No local cloning, no CLI tools needed.
-- Just paste this into a Snowsight worksheet and run as ACCOUNTADMIN.
--
-- This script:
--   1. Creates database, schemas, tables, and warehouse
--   2. Creates a Git Repository integration to GitHub
--   3. Deploys the Streamlit app directly from the Git repo
--   4. Sets up all required grants
-- ==============================================================================

USE ROLE ACCOUNTADMIN;

-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ 1. CREATE INFRASTRUCTURE                                           ║
-- ╚══════════════════════════════════════════════════════════════════════╝

-- Database and schemas
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_OPS_INTELLIGENCE;
USE DATABASE SNOWFLAKE_OPS_INTELLIGENCE;

CREATE SCHEMA IF NOT EXISTS APP_DATA;
CREATE SCHEMA IF NOT EXISTS APP_CONTEXT;
CREATE SCHEMA IF NOT EXISTS APP_ANALYTICS;

-- Warehouse (X-Small, auto-suspend 60s for cost efficiency)
CREATE WAREHOUSE IF NOT EXISTS SNOWOPS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'SnowOps Intelligence app warehouse';

USE WAREHOUSE SNOWOPS_WH;


-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ 2. CORE TABLES (from master_setup.sql)                             ║
-- ╚══════════════════════════════════════════════════════════════════════╝

-- APP_CONTEXT tables
CREATE TABLE IF NOT EXISTS APP_CONTEXT.APP_CONFIG (
    CONFIG_KEY VARCHAR(100) PRIMARY KEY,
    CONFIG_VALUE VARIANT,
    CATEGORY VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_CONTEXT.PLATFORM_SETTINGS (
    SETTING_KEY VARCHAR(100) PRIMARY KEY,
    SETTING_VALUE VARCHAR(1000),
    DESCRIPTION VARCHAR(500),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_CONTEXT.WAREHOUSE_CONTEXT (
    WAREHOUSE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    WAREHOUSE_NAME VARCHAR(255) NOT NULL UNIQUE,
    PURPOSE VARCHAR(50) DEFAULT 'GENERAL',
    SIZE VARCHAR(20),
    COST_PROFILE VARCHAR(20) DEFAULT 'BALANCED',
    CONCURRENCY_TOLERANCE VARCHAR(20) DEFAULT 'MEDIUM',
    OPTIMAL_HOURS_JSON VARCHAR(500),
    AUTO_SUSPEND_SECONDS NUMBER,
    OWNER_TEAM VARCHAR(255),
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_CONTEXT.TABLE_CONTEXT (
    TABLE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    DATABASE_NAME VARCHAR(255) NOT NULL,
    SCHEMA_NAME VARCHAR(255) NOT NULL,
    TABLE_NAME VARCHAR(255) NOT NULL,
    SIZE_BYTES NUMBER,
    ROW_COUNT NUMBER,
    LAST_MODIFIED TIMESTAMP_NTZ,
    CLUSTER_KEYS VARCHAR(1000),
    PARTITION_COUNT NUMBER,
    ACCESS_FREQUENCY VARCHAR(20) DEFAULT 'UNKNOWN',
    USER_FRESHNESS_REQUIREMENT VARCHAR(20) DEFAULT 'DAILY',
    IS_CRITICAL BOOLEAN DEFAULT FALSE,
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (DATABASE_NAME, SCHEMA_NAME, TABLE_NAME)
);

CREATE TABLE IF NOT EXISTS APP_CONTEXT.QUERY_CONTEXT (
    QUERY_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_HASH VARCHAR(64),
    QUERY_PARAMETERIZED_HASH VARCHAR(64),
    QUERY_TEXT_SAMPLE VARCHAR(10000),
    WORKLOAD_TYPE VARCHAR(50) DEFAULT 'ANALYTICAL',
    COST_TOLERANCE VARCHAR(20) DEFAULT 'BALANCED',
    LATENCY_TOLERANCE_MS NUMBER,
    EXPECTED_RUNTIME_MS NUMBER,
    RECOMMENDED_WAREHOUSE VARCHAR(255),
    OPTIMIZATION_NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (QUERY_PARAMETERIZED_HASH)
);

CREATE TABLE IF NOT EXISTS APP_CONTEXT.TEAM_ATTRIBUTION (
    ATTRIBUTION_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL UNIQUE,
    TEAM_NAME VARCHAR(255),
    DEPARTMENT VARCHAR(255),
    COST_CENTER VARCHAR(100),
    BUDGET_LIMIT_CREDITS FLOAT,
    ALERT_THRESHOLD_PERCENT INTEGER DEFAULT 80,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_CONTEXT.BUDGET_ALERTS (
    ALERT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    ALERT_NAME VARCHAR(255) NOT NULL,
    ALERT_TYPE VARCHAR(50),
    TARGET_NAME VARCHAR(255),
    THRESHOLD_CREDITS FLOAT,
    THRESHOLD_PERCENTAGE FLOAT,
    THRESHOLD_VALUE FLOAT,
    CONDITION_OP VARCHAR(50) DEFAULT '>',
    NOTIFICATION_CHANNEL VARCHAR(50) DEFAULT 'DASHBOARD',
    NOTIFICATION_CONFIG VARCHAR(2000),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    LAST_TRIGGERED TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_CONTEXT.OPTIMIZATION_HISTORY (
    OPTIMIZATION_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_HASH VARCHAR(64),
    RECOMMENDATION_TYPE VARCHAR(100),
    RECOMMENDATION_TEXT VARCHAR(4000),
    ESTIMATED_SAVINGS_CREDITS FLOAT,
    ACTUAL_SAVINGS_CREDITS FLOAT,
    STATUS VARCHAR(20) DEFAULT 'SUGGESTED',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    APPLIED_AT TIMESTAMP_NTZ,
    VERIFIED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS APP_CONTEXT.NOTIFICATIONS_LOG (
    EVENT_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LEVEL VARCHAR(20),
    MESSAGE VARCHAR(500),
    CHANNEL VARCHAR(50) DEFAULT 'ALL'
);

CREATE TABLE IF NOT EXISTS APP_CONTEXT.ENFORCEMENT_LOG (
    EVENT_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ACTION VARCHAR(50),
    TARGET_ID VARCHAR(255),
    TEAM_NAME VARCHAR(100),
    REASON VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS APP_CONTEXT.AGENT_LOGS (
    LOG_ID VARCHAR(50) PRIMARY KEY,
    AGENT_ID VARCHAR(50),
    RUN_ID VARCHAR(50),
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STEP_NUMBER INT,
    TYPE VARCHAR(20),
    CONTENT VARCHAR(16777216),
    METADATA VARIANT
);

-- APP_ANALYTICS tables
CREATE TABLE IF NOT EXISTS APP_ANALYTICS.DAILY_COST_SNAPSHOT (
    SNAPSHOT_DATE DATE PRIMARY KEY,
    TOTAL_CREDITS_USED FLOAT,
    COMPUTE_CREDITS FLOAT,
    STORAGE_CREDITS FLOAT,
    CLOUD_SERVICES_CREDITS FLOAT,
    DATA_TRANSFER_CREDITS FLOAT,
    WAREHOUSE_COUNT NUMBER,
    QUERY_COUNT NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_ANALYTICS.WAREHOUSE_DAILY_METRICS (
    METRIC_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    METRIC_DATE DATE,
    WAREHOUSE_NAME VARCHAR(255),
    CREDITS_USED FLOAT,
    QUERY_COUNT NUMBER,
    AVG_EXECUTION_TIME_MS FLOAT,
    AVG_QUEUE_TIME_MS FLOAT,
    CACHE_HIT_RATIO FLOAT,
    BYTES_SCANNED NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (METRIC_DATE, WAREHOUSE_NAME)
);

CREATE TABLE IF NOT EXISTS APP_ANALYTICS.QUERY_PATTERN_ANALYTICS (
    PATTERN_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    ANALYSIS_DATE DATE,
    QUERY_PARAMETERIZED_HASH VARCHAR(64),
    EXECUTION_COUNT NUMBER,
    AVG_EXECUTION_TIME_MS FLOAT,
    AVG_BYTES_SCANNED NUMBER,
    AVG_CREDITS_USED FLOAT,
    CACHE_HIT_COUNT NUMBER,
    FAILURE_COUNT NUMBER,
    LAST_EXECUTED TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (ANALYSIS_DATE, QUERY_PARAMETERIZED_HASH)
);

CREATE TABLE IF NOT EXISTS APP_ANALYTICS.QUERY_BENCHMARK (
    BENCHMARK_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_TEXT VARCHAR(10000),
    QUERY_HASH VARCHAR(64),
    RUN_TYPE VARCHAR(20),
    PREDICTED_COST_CREDITS FLOAT,
    ACTUAL_COST_CREDITS FLOAT,
    PREDICTED_TIME_MS NUMBER,
    ACTUAL_TIME_MS NUMBER,
    BYTES_SCANNED NUMBER,
    WAREHOUSE_USED VARCHAR(255),
    WAREHOUSE_SIZE VARCHAR(20),
    OPTIMIZATION_APPLIED VARCHAR(1000),
    COST_SAVINGS_CREDITS FLOAT,
    TIME_SAVINGS_MS NUMBER,
    RUN_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_ANALYTICS.ALERT_LOG (
    ALERT_LOG_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    ALERT_NAME VARCHAR(255),
    TRIGGERED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DETAILS VARIANT
);

CREATE TABLE IF NOT EXISTS APP_ANALYTICS.AUTOPILOT_LOG (
    EVENT_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ACTION VARCHAR,
    REASON VARCHAR,
    WAREHOUSE_NAME VARCHAR,
    DETAILS VARIANT
);

CREATE TABLE IF NOT EXISTS APP_ANALYTICS.BI_DASHBOARDS (
    DASHBOARD_ID VARCHAR(50) PRIMARY KEY,
    DASHBOARD_NAME VARCHAR(255),
    DASHBOARD_CONFIG VARIANT,
    CREATED_BY VARCHAR(255),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_ANALYTICS.DQ_SCAN_RESULTS (
    SCAN_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    TABLE_SCHEMA VARCHAR(255),
    TABLE_NAME VARCHAR(255),
    COLUMN_NAME VARCHAR(255),
    NULL_COUNT NUMBER,
    NULL_PCT FLOAT,
    DISTINCT_COUNT NUMBER,
    DISTINCT_PCT FLOAT,
    SCAN_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_ANALYTICS.REPORT_USAGE (
    USAGE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    REPORT_NAME VARCHAR(255),
    REPORT_TYPE VARCHAR(50),
    USER_NAME VARCHAR(255),
    ACCESS_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SESSION_DURATION_SECONDS NUMBER,
    ACTIONS_PERFORMED NUMBER
);


-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ 3. DEFAULT DATA                                                    ║
-- ╚══════════════════════════════════════════════════════════════════════╝

INSERT INTO APP_CONTEXT.PLATFORM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION)
SELECT 'COST_PER_CREDIT', '3.00', 'Dollar cost per Snowflake credit'
WHERE NOT EXISTS (SELECT 1 FROM APP_CONTEXT.PLATFORM_SETTINGS WHERE SETTING_KEY = 'COST_PER_CREDIT');

INSERT INTO APP_CONTEXT.PLATFORM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION)
SELECT 'MONTHLY_BUDGET_CREDITS', '1000', 'Monthly credit budget limit'
WHERE NOT EXISTS (SELECT 1 FROM APP_CONTEXT.PLATFORM_SETTINGS WHERE SETTING_KEY = 'MONTHLY_BUDGET_CREDITS');

INSERT INTO APP_CONTEXT.BUDGET_ALERTS (ALERT_NAME, ALERT_TYPE, TARGET_NAME, THRESHOLD_CREDITS, THRESHOLD_PERCENTAGE, IS_ACTIVE)
SELECT 'Account Daily Limit', 'ACCOUNT', 'ACCOUNT', 10.0, 80.0, TRUE
WHERE NOT EXISTS (SELECT 1 FROM APP_CONTEXT.BUDGET_ALERTS WHERE ALERT_NAME = 'Account Daily Limit');


-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ 4. GRANTS                                                          ║
-- ╚══════════════════════════════════════════════════════════════════════╝

-- Grant ACCOUNT_USAGE access (required for cost/query/security views)
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE PUBLIC;

-- Grant app database access
GRANT USAGE ON DATABASE SNOWFLAKE_OPS_INTELLIGENCE TO ROLE PUBLIC;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SNOWFLAKE_OPS_INTELLIGENCE TO ROLE PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA APP_CONTEXT TO ROLE PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA APP_ANALYTICS TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA APP_DATA TO ROLE PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA APP_CONTEXT TO ROLE PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA APP_ANALYTICS TO ROLE PUBLIC;


-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ 5. GIT REPOSITORY INTEGRATION (Public Repo Deploy)                   ║
-- ╚══════════════════════════════════════════════════════════════════════╝

-- Create the API Integration for the public GitHub repository
CREATE OR REPLACE API INTEGRATION SNOWOPS_GIT_INTEGRATION
  API_PROVIDER = GIT_HTTPS_API
  API_ALLOWED_PREFIXES = ('https://github.com/devbysatyam/')
  ENABLED = TRUE;

-- Stage for the app files
CREATE STAGE IF NOT EXISTS APP_ANALYTICS.STREAMLIT_STAGE
  DIRECTORY = (ENABLE = TRUE);

-- Git Repository object linking to the public repo
CREATE OR REPLACE GIT REPOSITORY APP_DATA.SNOWOPS_REPO
  API_INTEGRATION = SNOWOPS_GIT_INTEGRATION
  ORIGIN = 'https://github.com/devbysatyam/snowflake_ops_intelligence.git';

-- Fetch latest from GitHub
ALTER GIT REPOSITORY APP_DATA.SNOWOPS_REPO FETCH;


-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ 6. DEPLOY STREAMLIT APP FROM GIT                                   ║
-- ╚══════════════════════════════════════════════════════════════════════╝

-- Create the Streamlit app directly from the Git repository
CREATE OR REPLACE STREAMLIT APP_ANALYTICS.SNOWFLAKE_OPS_INTELLIGENCE
  ROOT_LOCATION = '@APP_DATA.SNOWOPS_REPO/branches/main/app'
  MAIN_FILE = 'streamlit_app.py'
  QUERY_WAREHOUSE = SNOWOPS_WH
  TITLE = 'Snowflake Ops Intelligence'
  COMMENT = 'Deployed via Git integration — github.com/devbysatyam/snowflake_ops_intelligence';

-- Grant access to the Streamlit app
GRANT USAGE ON STREAMLIT APP_ANALYTICS.SNOWFLAKE_OPS_INTELLIGENCE TO ROLE PUBLIC;


-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ SETUP COMPLETE ✅                                                  ║
-- ╚══════════════════════════════════════════════════════════════════════╝
-- Your app is now live! Navigate to:
--   Snowsight → Projects → Streamlit → SNOWFLAKE_OPS_INTELLIGENCE
--
-- To update the app when new code is pushed to GitHub:
--   ALTER GIT REPOSITORY APP_DATA.SNOWOPS_REPO FETCH;
--   (The Streamlit app auto-reads from the latest fetched content)
-- ==============================================================================

SELECT '✅ SnowOps Intelligence deployed successfully! Open Snowsight → Streamlit to access your app.' AS STATUS;
